services:
  node: 
    image: node:latest
    command: sh -c "npm install && node app.js" 
    ports:
      - 3000:3000
    working_dir: "/app"
    volumes:
      - .:/app
    environment:
      - MONGO=mongodb://admin:pass@mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
  